<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net48</TargetFramework>
    <UseWindowsForms>true</UseWindowsForms>
    <AssemblyName>Launcher</AssemblyName>
    <Nullable>disable</Nullable>
    <ApplicationIcon>../images/encendido.ico</ApplicationIcon>
  </PropertyGroup>

  <ItemGroup>
    <Reference Include="System.Net.Http" />
  </ItemGroup>

</Project>